# Generated by Django 2.0.2 on 2018-03-03 13:41

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountType', models.CharField(choices=[('Customer', 'Customer'), ('Product Manager', 'Product Manager'), ('Accounting Manager', 'Accounting Manager'), ('Admin', 'Admin')], default='Customer', max_length=25)),
                ('firstName', models.CharField(max_length=25)),
                ('middleInitial', models.CharField(max_length=10)),
                ('lastName', models.CharField(max_length=25)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('BhouseNo', models.IntegerField()),
                ('Bstreet', models.CharField(max_length=50)),
                ('Bsubdivision', models.CharField(max_length=50)),
                ('Bcity', models.CharField(max_length=50)),
                ('BpostalCode', models.IntegerField()),
                ('Bcountry', django_countries.fields.CountryField(max_length=2)),
                ('ShouseNo', models.IntegerField()),
                ('Sstreet', models.CharField(max_length=50)),
                ('Ssubdivision', models.CharField(max_length=50)),
                ('Scity', models.CharField(max_length=50)),
                ('SpostalCode', models.IntegerField()),
                ('Scountry', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
