# Generated by Django 2.0.2 on 2018-03-13 15:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20180312_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvv', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(3)])),
                ('card_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(16), django.core.validators.MaxValueValidator(16)])),
                ('exp_date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.User')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trans_num', models.IntegerField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('trans_date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.Items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.User')),
            ],
        ),
    ]
