# Generated by Django 2.0.2 on 2018-03-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_creditinfo_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_num',
            field=models.IntegerField(),
        ),
    ]
