# Generated by Django 2.0.2 on 2018-03-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20180313_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='A review', max_length=120),
        ),
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
